### ISSUE TITLE
Ui not useable on smartphone

### ISSUE THREAD

**Issue by Langlaeufer** [osmberlin/osm-traffic-sign-tool#55] opened 2024-10-30 06:52 UTC
Beta 2.1.0
Selection of signs not visable

Current Google chrome
Android 14

![Screenshot_20241030_074828_Chrome](https://github.com/user-attachments/assets/9e98643a-3d64-4163-b7db-683b66c2d146)

![Screenshot_20241030_075726_Chrome](https://github.com/user-attachments/assets/0e0ce269-ae46-4807-a92f-784ffa5b2a3a)

**Comment by tordans** [comment] 2024-10-30 09:58
Thanks for the ping, this is a duplicate of https://github.com/osmberlin/osm-traffic-sign-tool/issues/55 which I will close now as well. The UI is now visible on mobile. Still not optimized in any way, but that is out of scope for now…

https://trafficsigns.osm-verkehrswende.org/DE

**Closed by tordans** 2024-10-30 09:58 UTC
